### ISSUE TITLE
Prompts

### ISSUE THREAD

**Issue by ivan-kleshnin** [TylorS/reginn#5]
Hi, Tylor. Great API, I've really enjoyed reading through the docs! 

Do you plan to add prompts?
### Motivation

Some CLI operations are destructive and need to be additionally confirmed by user.
Even better when such confirmations provide additional information. 

I imagine something like:

```
$ node ./cli.js rm */*.txt
```

```
- folder1/foo.txt
- folder2/bar.txt
- bazz.txt
are going to be removed
Confirm (y/n): _ 
```

**Comment by TylorS** [comment]
Hey @ivan-kleshnin thanks for the kind words, I hope that this proves useful to you in some way.

I've not really thought about adding prompts. I was really trying to keep things minimal. By documenting the types the library works, I figured that would make it easier to extend the library. For example you could create a custom `run()` and `commandWithPrompts()` maybe, but that's probably more work than it's worth in many cases. 

I'd probably suggest using something like [`inquirer`](https://github.com/SBoudrias/Inquirer.js/)
Your proposed command might look something like

``` js
import { command, alias, run, asPromise } from 'reginn'
import { prompt } from 'inquirer'
import rimraf from 'rimraf'

const remove = command(alias('rm'))

asPromise(remove)
  .then(({ args }) => {

    const areYouSure = {
      type: 'confirm',
      name: 'confirm',
      message: `\n - ${args.join('\n - ')}\n are going to be removed\n Confirm (y/n):`  
    }

    prompt([ areYouSure ]).then(answers => {
      if (answer.confirm) {
        args.forEach(file => rimraf(file, (err) => {
          if (err) throw err
        }))
      }
    })
  })

run(remove) 
```

I don't have any idea if this example will actually run, but I hope it demonstrates how it could be possible to include prompts inside of your handler functions. I think this makes assumptions about your shell though too, as `zsh` will automatically expand `*/*.txt` to the full paths of all the files.

I'm going to close this as a discussion for now, please reopen if you think this is an invalid answer, and feel free to continue the discussion.

**Comment by ivan-kleshnin** [comment]
Thanks. I'm going to try this and post about positive or negative results.
